# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gir.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 581)
        MainWindow.setMinimumSize(QtCore.QSize(793, 581))
        MainWindow.setMaximumSize(QtCore.QSize(793, 581))
        MainWindow.setStyleSheet("QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"QHeaderView {\n"
"    background-color: #fff;\n"
"    font-size:13px;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"    color: #fff;\n"
"    border-style: solid;\n"
"    background-color: qlineargradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                        stop: 0 #4287ff, stop: 1 #356ccc);\n"
" }\n"
"QTableView {\n"
"    border: 2px solid #3873d9;\n"
"    border-top-color: #4287ff;\n"
"    border-radius: 4px;\n"
"    background-color: #fff;\n"
"    background-image: url(:/img/other/background.png);\n"
"    gridline-color: #777;\n"
"    selection-background-color: #ccdfff;\n"
"    color:#333;\n"
"    font-size:12px;\n"
" }\n"
"QSpinBox{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox:hover{\n"
"    border: 2px solid gray;\n"
"    border-radius: 4px;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid gray;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton{\n"
"  position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 3px;\n"
"  background: linear-gradient(rgb(110,112,120), rgb(81,81,86)) rgb(110,112,120);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover:not(:active) {\n"
"  background-color: green;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  top: 1px;\n"
"  background: linear-gradient(rgb(76,77,82), rgb(56,57,62)) rgb(76,77,82);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plot6 = QtWidgets.QTabWidget(self.centralwidget)
        self.plot6.setGeometry(QtCore.QRect(0, 0, 781, 541))
        self.plot6.setStyleSheet("")
        self.plot6.setObjectName("plot6")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plot1 = QtWidgets.QWidget(self.tab)
        self.plot1.setGeometry(QtCore.QRect(0, 10, 471, 441))
        self.plot1.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 4px;")
        self.plot1.setObjectName("plot1")
        self.label_8 = QtWidgets.QLabel(self.plot1)
        self.label_8.setGeometry(QtCore.QRect(490, 200, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(490, 10, 261, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.step1 = QtWidgets.QLineEdit(self.tab)
        self.step1.setGeometry(QtCore.QRect(520, 30, 243, 18))
        self.step1.setStyleSheet("")
        self.step1.setObjectName("step1")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(490, 30, 21, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(490, 60, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(490, 80, 271, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.startX1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.startX1.setObjectName("startX1")
        self.gridLayout.addWidget(self.startX1, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.startY1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.startY1.setObjectName("startY1")
        self.gridLayout.addWidget(self.startY1, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(490, 160, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(490, 180, 47, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.StartIter1 = QtWidgets.QLineEdit(self.tab)
        self.StartIter1.setGeometry(QtCore.QRect(520, 180, 243, 18))
        self.StartIter1.setObjectName("StartIter1")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(490, 340, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.ButtStart1 = QtWidgets.QPushButton(self.tab)
        self.ButtStart1.setGeometry(QtCore.QRect(0, 470, 471, 41))
        self.ButtStart1.setObjectName("ButtStart1")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setGeometry(QtCore.QRect(490, 210, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("")
        self.label_39.setObjectName("label_39")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(490, 230, 271, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(490, 250, 271, 91))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_10.addWidget(self.label_40, 0, 0, 1, 1)
        self.StrSys1 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.StrSys1.setReadOnly(True)
        self.StrSys1.setObjectName("StrSys1")
        self.gridLayout_10.addWidget(self.StrSys1, 0, 1, 1, 1)
        self.StrSys2 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.StrSys2.setReadOnly(True)
        self.StrSys2.setObjectName("StrSys2")
        self.gridLayout_10.addWidget(self.StrSys2, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 1, 0, 1, 1)
        self.tableView1 = QtWidgets.QTableWidget(self.tab)
        self.tableView1.setGeometry(QtCore.QRect(490, 360, 271, 151))
        self.tableView1.setObjectName("tableView1")
        self.tableView1.setColumnCount(0)
        self.tableView1.setRowCount(0)
        self.plot6.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.plot2 = QtWidgets.QWidget(self.tab_3)
        self.plot2.setGeometry(QtCore.QRect(0, 10, 421, 451))
        self.plot2.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 4px;")
        self.plot2.setObjectName("plot2")
        self.ButtStart2 = QtWidgets.QPushButton(self.tab_3)
        self.ButtStart2.setGeometry(QtCore.QRect(0, 470, 421, 41))
        self.ButtStart2.setObjectName("ButtStart2")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(430, 10, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(430, 30, 331, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.system2D1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.system2D1.setObjectName("system2D1")
        self.gridLayout_2.addWidget(self.system2D1, 0, 1, 1, 1)
        self.system2D2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.system2D2.setObjectName("system2D2")
        self.gridLayout_2.addWidget(self.system2D2, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(430, 170, 261, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(430, 180, 331, 41))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.step2D = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.step2D.setObjectName("step2D")
        self.gridLayout_3.addWidget(self.step2D, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(430, 90, 331, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(430, 110, 331, 61))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.helperW2D = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.helperW2D.setObjectName("helperW2D")
        self.gridLayout_4.addWidget(self.helperW2D, 0, 1, 1, 1)
        self.helperV2D = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.helperV2D.setObjectName("helperV2D")
        self.gridLayout_4.addWidget(self.helperV2D, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(430, 270, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(430, 290, 331, 80))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Start2DX = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Start2DX.setObjectName("Start2DX")
        self.gridLayout_5.addWidget(self.Start2DX, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.Start2DY = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Start2DY.setObjectName("Start2DY")
        self.gridLayout_5.addWidget(self.Start2DY, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(430, 360, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(430, 380, 331, 131))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_87 = QtWidgets.QLabel(self.tab_3)
        self.label_87.setGeometry(QtCore.QRect(430, 220, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(430, 230, 331, 41))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_88 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.gridLayout_23.addWidget(self.label_88, 0, 0, 1, 1)
        self.StartIter2 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.StartIter2.setObjectName("StartIter2")
        self.gridLayout_23.addWidget(self.StartIter2, 0, 1, 1, 1)
        self.plot6.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plot3 = QtWidgets.QWidget(self.tab_2)
        self.plot3.setGeometry(QtCore.QRect(10, 10, 451, 451))
        self.plot3.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 4px;")
        self.plot3.setObjectName("plot3")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(470, 10, 291, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(470, 30, 301, 81))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 0, 1, 1)
        self.system3D1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.system3D1.setObjectName("system3D1")
        self.gridLayout_6.addWidget(self.system3D1, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 1, 0, 1, 1)
        self.system3D2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.system3D2.setObjectName("system3D2")
        self.gridLayout_6.addWidget(self.system3D2, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 2, 0, 1, 1)
        self.system3D3 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.system3D3.setObjectName("system3D3")
        self.gridLayout_6.addWidget(self.system3D3, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(470, 120, 301, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(470, 140, 301, 100))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 0, 0, 1, 1)
        self.helperV3D = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.helperV3D.setObjectName("helperV3D")
        self.gridLayout_7.addWidget(self.helperV3D, 1, 1, 1, 1)
        self.helperW3D = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.helperW3D.setObjectName("helperW3D")
        self.gridLayout_7.addWidget(self.helperW3D, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 3, 0, 1, 1)
        self.helperAlfa3D = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.helperAlfa3D.setObjectName("helperAlfa3D")
        self.gridLayout_7.addWidget(self.helperAlfa3D, 2, 1, 1, 1)
        self.helperBeta3D = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.helperBeta3D.setObjectName("helperBeta3D")
        self.gridLayout_7.addWidget(self.helperBeta3D, 3, 1, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(470, 250, 301, 261))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 261, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 281, 41))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 0, 0, 1, 1)
        self.step3D = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.step3D.setObjectName("step3D")
        self.gridLayout_8.addWidget(self.step3D, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 80, 281, 101))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.StartX3D = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.StartX3D.setObjectName("StartX3D")
        self.gridLayout_9.addWidget(self.StartX3D, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_9.addWidget(self.label_35, 1, 0, 1, 1)
        self.StartY3D = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.StartY3D.setObjectName("StartY3D")
        self.gridLayout_9.addWidget(self.StartY3D, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_9.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 2, 0, 1, 1)
        self.StartZ3D = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.StartZ3D.setObjectName("StartZ3D")
        self.gridLayout_9.addWidget(self.StartZ3D, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(10, 190, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(10, 210, 47, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.StartIter3D = QtWidgets.QLineEdit(self.tab_4)
        self.StartIter3D.setGeometry(QtCore.QRect(40, 210, 251, 20))
        self.StartIter3D.setObjectName("StartIter3D")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setGeometry(QtCore.QRect(10, 0, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 20, 281, 211))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.ButtStart3 = QtWidgets.QPushButton(self.tab_2)
        self.ButtStart3.setGeometry(QtCore.QRect(0, 470, 461, 41))
        self.ButtStart3.setObjectName("ButtStart3")
        self.plot6.addTab(self.tab_2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayoutWidget_16 = QtWidgets.QWidget(self.tab_8)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(10, 10, 261, 341))
        self.gridLayoutWidget_16.setObjectName("gridLayoutWidget_16")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_97 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        self.gridLayout_19.addWidget(self.label_97, 7, 0, 1, 1)
        self.alfa2ddy = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.alfa2ddy.setObjectName("alfa2ddy")
        self.gridLayout_19.addWidget(self.alfa2ddy, 5, 1, 1, 2)
        self.label_98 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_98.setFont(font)
        self.label_98.setObjectName("label_98")
        self.gridLayout_19.addWidget(self.label_98, 12, 0, 1, 5)
        self.label_94 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.gridLayout_19.addWidget(self.label_94, 5, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_89 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.gridLayout_20.addWidget(self.label_89, 0, 0, 1, 1)
        self.stepddy = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.stepddy.setObjectName("stepddy")
        self.gridLayout_20.addWidget(self.stepddy, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_20, 11, 0, 1, 2)
        self.label_90 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.gridLayout_19.addWidget(self.label_90, 4, 0, 1, 1)
        self.alfa3ddy = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.alfa3ddy.setObjectName("alfa3ddy")
        self.gridLayout_19.addWidget(self.alfa3ddy, 6, 1, 1, 2)
        self.InitFunc1 = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.InitFunc1.setObjectName("InitFunc1")
        self.gridLayout_19.addWidget(self.InitFunc1, 9, 1, 1, 2)
        self.label_91 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_91.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.gridLayout_19.addWidget(self.label_91, 3, 0, 1, 5)
        self.alfa1ddy = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.alfa1ddy.setObjectName("alfa1ddy")
        self.gridLayout_19.addWidget(self.alfa1ddy, 4, 1, 1, 2)
        self.label_93 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.gridLayout_19.addWidget(self.label_93, 10, 0, 1, 5)
        self.label_92 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.gridLayout_19.addWidget(self.label_92, 9, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.gridLayout_19.addWidget(self.label_80, 6, 0, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.Sys1Ddy = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.Sys1Ddy.setObjectName("Sys1Ddy")
        self.gridLayout_21.addWidget(self.Sys1Ddy, 0, 1, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_96.setFont(font)
        self.label_96.setObjectName("label_96")
        self.gridLayout_21.addWidget(self.label_96, 0, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_21, 2, 0, 1, 3)
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_78.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.gridLayout_19.addWidget(self.label_78, 0, 0, 1, 5)
        self.label_95 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setObjectName("label_95")
        self.gridLayout_19.addWidget(self.label_95, 8, 0, 1, 5)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.Iterddy = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.Iterddy.setObjectName("Iterddy")
        self.gridLayout_22.addWidget(self.Iterddy, 0, 1, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayout_22.addWidget(self.label_100, 0, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_22, 13, 0, 1, 2)
        self.helperW = QtWidgets.QLineEdit(self.gridLayoutWidget_16)
        self.helperW.setObjectName("helperW")
        self.gridLayout_19.addWidget(self.helperW, 7, 1, 1, 2)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 370, 261, 131))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.label_75 = QtWidgets.QLabel(self.tab_8)
        self.label_75.setGeometry(QtCore.QRect(10, 355, 261, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.widget = QtWidgets.QWidget(self.tab_8)
        self.widget.setGeometry(QtCore.QRect(280, 10, 491, 451))
        self.widget.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 4px;")
        self.widget.setObjectName("widget")
        self.ButtStart6 = QtWidgets.QPushButton(self.tab_8)
        self.ButtStart6.setGeometry(QtCore.QRect(280, 465, 491, 31))
        self.ButtStart6.setObjectName("ButtStart6")
        self.plot6.addTab(self.tab_8, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.tab_7)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(10, 0, 261, 471))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_99 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.gridLayout_15.addWidget(self.label_99, 10, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_15.addWidget(self.label_74, 13, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_84 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.gridLayout_18.addWidget(self.label_84, 0, 0, 1, 1)
        self.stepddy2D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.stepddy2D.setObjectName("stepddy2D")
        self.gridLayout_18.addWidget(self.stepddy2D, 0, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_18, 16, 0, 1, 2)
        self.beta32D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.beta32D.setObjectName("beta32D")
        self.gridLayout_15.addWidget(self.beta32D, 9, 1, 1, 2)
        self.alfa32D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.alfa32D.setObjectName("alfa32D")
        self.gridLayout_15.addWidget(self.alfa32D, 6, 1, 1, 2)
        self.alfa22D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.alfa22D.setObjectName("alfa22D")
        self.gridLayout_15.addWidget(self.alfa22D, 5, 1, 1, 2)
        self.label_86 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.gridLayout_15.addWidget(self.label_86, 8, 0, 1, 1)
        self.beta12D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.beta12D.setObjectName("beta12D")
        self.gridLayout_15.addWidget(self.beta12D, 7, 1, 1, 2)
        self.alfa12D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.alfa12D.setObjectName("alfa12D")
        self.gridLayout_15.addWidget(self.alfa12D, 4, 1, 1, 2)
        self.label_85 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.gridLayout_15.addWidget(self.label_85, 7, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_15.addWidget(self.label_67, 9, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.gridLayout_15.addWidget(self.label_72, 0, 0, 1, 5)
        self.label_70 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_15.addWidget(self.label_70, 6, 0, 1, 1)
        self.InitFunc22D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.InitFunc22D.setObjectName("InitFunc22D")
        self.gridLayout_15.addWidget(self.InitFunc22D, 14, 1, 1, 2)
        self.label_71 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_15.addWidget(self.label_71, 4, 0, 1, 1)
        self.beta22D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.beta22D.setObjectName("beta22D")
        self.gridLayout_15.addWidget(self.beta22D, 8, 1, 1, 2)
        self.label_73 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_73.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_15.addWidget(self.label_73, 3, 0, 1, 5)
        self.label_76 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.gridLayout_15.addWidget(self.label_76, 12, 0, 1, 5)
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_15.addWidget(self.label_68, 15, 0, 1, 5)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.gridLayout_16.addWidget(self.label_79, 0, 0, 1, 1)
        self.Sys1Ddy2D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.Sys1Ddy2D.setObjectName("Sys1Ddy2D")
        self.gridLayout_16.addWidget(self.Sys1Ddy2D, 0, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_16.addWidget(self.label_81, 1, 0, 1, 1)
        self.Sys2Ddy2D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.Sys2Ddy2D.setObjectName("Sys2Ddy2D")
        self.gridLayout_16.addWidget(self.Sys2Ddy2D, 1, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_16, 2, 0, 1, 3)
        self.label_77 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.gridLayout_15.addWidget(self.label_77, 14, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.Iterddy2D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.Iterddy2D.setObjectName("Iterddy2D")
        self.gridLayout_17.addWidget(self.Iterddy2D, 0, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.gridLayout_17.addWidget(self.label_83, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_17, 18, 0, 1, 2)
        self.label_82 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_15.addWidget(self.label_82, 17, 0, 1, 5)
        self.label_69 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_15.addWidget(self.label_69, 5, 0, 1, 1)
        self.InitFunc12D = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.InitFunc12D.setObjectName("InitFunc12D")
        self.gridLayout_15.addWidget(self.InitFunc12D, 13, 1, 1, 2)
        self.label_101 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridLayout_15.addWidget(self.label_101, 11, 0, 1, 1)
        self.helperW2 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.helperW2.setObjectName("helperW2")
        self.gridLayout_15.addWidget(self.helperW2, 10, 1, 1, 2)
        self.helperV2 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.helperV2.setObjectName("helperV2")
        self.gridLayout_15.addWidget(self.helperV2, 11, 1, 1, 2)
        self.plot4 = QtWidgets.QWidget(self.tab_7)
        self.plot4.setGeometry(QtCore.QRect(280, 10, 491, 311))
        self.plot4.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 4px;")
        self.plot4.setObjectName("plot4")
        self.label_66 = QtWidgets.QLabel(self.tab_7)
        self.label_66.setGeometry(QtCore.QRect(280, 330, 491, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_4.setGeometry(QtCore.QRect(280, 350, 491, 111))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.ButtStart4 = QtWidgets.QPushButton(self.tab_7)
        self.ButtStart4.setGeometry(QtCore.QRect(280, 470, 491, 31))
        self.ButtStart4.setObjectName("ButtStart4")
        self.plot6.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(10, 0, 261, 515))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_11.addWidget(self.label_54, 10, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_11.addWidget(self.label_53, 9, 0, 1, 1)
        self.InitFunc23D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.InitFunc23D.setObjectName("InitFunc23D")
        self.gridLayout_11.addWidget(self.InitFunc23D, 15, 1, 1, 3)
        self.InitFunc33D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.InitFunc33D.setObjectName("InitFunc33D")
        self.gridLayout_11.addWidget(self.InitFunc33D, 16, 1, 1, 3)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_11.addWidget(self.label_61, 17, 0, 1, 6)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_11.addWidget(self.label_49, 5, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_11.addWidget(self.label_50, 6, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_11.addWidget(self.label_46, 4, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_11.addWidget(self.label_47, 0, 0, 1, 6)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_11.addWidget(self.label_48, 3, 0, 1, 6)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 14, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 11, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_11.addWidget(self.label_43, 13, 0, 1, 6)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 15, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_11.addWidget(self.label_57, 16, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_12.addWidget(self.label_58, 0, 0, 1, 1)
        self.Sys1Ddy3D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.Sys1Ddy3D.setObjectName("Sys1Ddy3D")
        self.gridLayout_12.addWidget(self.Sys1Ddy3D, 0, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_12.addWidget(self.label_60, 2, 0, 1, 1)
        self.Sys3Ddy3D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.Sys3Ddy3D.setObjectName("Sys3Ddy3D")
        self.gridLayout_12.addWidget(self.Sys3Ddy3D, 2, 1, 1, 1)
        self.Sys2Ddy3D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.Sys2Ddy3D.setObjectName("Sys2Ddy3D")
        self.gridLayout_12.addWidget(self.Sys2Ddy3D, 1, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_12.addWidget(self.label_59, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 2, 0, 1, 4)
        self.InitFunc13D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.InitFunc13D.setObjectName("InitFunc13D")
        self.gridLayout_11.addWidget(self.InitFunc13D, 14, 1, 1, 3)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_11.addWidget(self.label_63, 19, 0, 1, 6)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Iterddy3D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.Iterddy3D.setObjectName("Iterddy3D")
        self.gridLayout_14.addWidget(self.Iterddy3D, 0, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_14.addWidget(self.label_65, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_14, 20, 0, 1, 2)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_13.addWidget(self.label_62, 0, 0, 1, 1)
        self.stepddy3D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.stepddy3D.setObjectName("stepddy3D")
        self.gridLayout_13.addWidget(self.stepddy3D, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_13, 18, 0, 1, 2)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_11.addWidget(self.label_51, 7, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_11.addWidget(self.label_52, 8, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_11.addWidget(self.label_56, 12, 0, 1, 1)
        self.gamma33D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.gamma33D.setObjectName("gamma33D")
        self.gridLayout_11.addWidget(self.gamma33D, 12, 1, 1, 3)
        self.gamma23D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.gamma23D.setObjectName("gamma23D")
        self.gridLayout_11.addWidget(self.gamma23D, 11, 1, 1, 3)
        self.gamma13D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.gamma13D.setObjectName("gamma13D")
        self.gridLayout_11.addWidget(self.gamma13D, 10, 1, 1, 3)
        self.beta33D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.beta33D.setObjectName("beta33D")
        self.gridLayout_11.addWidget(self.beta33D, 9, 1, 1, 3)
        self.beta23D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.beta23D.setObjectName("beta23D")
        self.gridLayout_11.addWidget(self.beta23D, 8, 1, 1, 3)
        self.beta13D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.beta13D.setObjectName("beta13D")
        self.gridLayout_11.addWidget(self.beta13D, 7, 1, 1, 3)
        self.alfa33D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.alfa33D.setObjectName("alfa33D")
        self.gridLayout_11.addWidget(self.alfa33D, 6, 1, 1, 3)
        self.alfa23D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.alfa23D.setObjectName("alfa23D")
        self.gridLayout_11.addWidget(self.alfa23D, 5, 1, 1, 3)
        self.alfa13D = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.alfa13D.setObjectName("alfa13D")
        self.gridLayout_11.addWidget(self.alfa13D, 4, 1, 1, 3)
        self.plot5 = QtWidgets.QWidget(self.tab_6)
        self.plot5.setGeometry(QtCore.QRect(280, 10, 491, 311))
        self.plot5.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 4px;")
        self.plot5.setObjectName("plot5")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_3.setGeometry(QtCore.QRect(280, 340, 491, 131))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.label_64 = QtWidgets.QLabel(self.tab_6)
        self.label_64.setGeometry(QtCore.QRect(280, 323, 491, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.ButtStart5 = QtWidgets.QPushButton(self.tab_6)
        self.ButtStart5.setGeometry(QtCore.QRect(280, 472, 491, 31))
        self.ButtStart5.setObjectName("ButtStart5")
        self.plot6.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.plot6.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Построение численного решения систем ОДУ"))
        self.label_8.setText(_translate("MainWindow", "Таблица вычисленных значений :"))
        self.label.setText(_translate("MainWindow", "Set grid integration step :"))
        self.label_2.setText(_translate("MainWindow", "h ="))
        self.label_3.setText(_translate("MainWindow", "Set the initial system conditions :"))
        self.label_4.setText(_translate("MainWindow", "x = "))
        self.label_5.setText(_translate("MainWindow", "y ="))
        self.label_6.setText(_translate("MainWindow", "Set the number of iterations :"))
        self.label_7.setText(_translate("MainWindow", "N ="))
        self.label_9.setText(_translate("MainWindow", "Value table :"))
        self.ButtStart1.setText(_translate("MainWindow", "Run"))
        self.label_39.setText(_translate("MainWindow", "Choose system number :"))
        self.label_40.setText(_translate("MainWindow", "x\' ="))
        self.label_41.setText(_translate("MainWindow", "y\' ="))
        self.plot6.setTabText(self.plot6.indexOf(self.tab), _translate("MainWindow", " BasicTestingUnit"))
        self.ButtStart2.setText(_translate("MainWindow", "Run"))
        self.label_10.setText(_translate("MainWindow", "Enter a system of differential equations :"))
        self.label_11.setText(_translate("MainWindow", "x\' ="))
        self.label_12.setText(_translate("MainWindow", "y\' ="))
        self.label_13.setText(_translate("MainWindow", "Set grid integration step :"))
        self.label_14.setText(_translate("MainWindow", "h ="))
        self.label_15.setText(_translate("MainWindow", "Enter auxiliary variables (No more that 2) :"))
        self.label_16.setText(_translate("MainWindow", "w ="))
        self.label_17.setText(_translate("MainWindow", "v ="))
        self.label_18.setText(_translate("MainWindow", "Set the initial system conditions :"))
        self.label_19.setText(_translate("MainWindow", "x = "))
        self.label_20.setText(_translate("MainWindow", "y ="))
        self.label_21.setText(_translate("MainWindow", "Value table :"))
        self.label_87.setText(_translate("MainWindow", "Set the number of iterations :"))
        self.label_88.setText(_translate("MainWindow", "N ="))
        self.plot6.setTabText(self.plot6.indexOf(self.tab_3), _translate("MainWindow", " Numerical solution of two-dimensional systems"))
        self.label_22.setText(_translate("MainWindow", "Enter a system of differential equations :"))
        self.label_23.setText(_translate("MainWindow", "x\' ="))
        self.label_24.setText(_translate("MainWindow", "y\' ="))
        self.label_25.setText(_translate("MainWindow", "z\' ="))
        self.label_26.setText(_translate("MainWindow", "Enter auxiliary variables (No more that 2) :"))
        self.label_29.setText(_translate("MainWindow", "alfa ="))
        self.label_28.setText(_translate("MainWindow", "v ="))
        self.label_27.setText(_translate("MainWindow", "w ="))
        self.label_30.setText(_translate("MainWindow", "beta ="))
        self.label_31.setText(_translate("MainWindow", "Set grid integration step :"))
        self.label_32.setText(_translate("MainWindow", "h ="))
        self.label_33.setText(_translate("MainWindow", "Set the initial system conditions :"))
        self.label_35.setText(_translate("MainWindow", "y ="))
        self.label_34.setText(_translate("MainWindow", "x = "))
        self.label_42.setText(_translate("MainWindow", "z ="))
        self.label_36.setText(_translate("MainWindow", "Set the number of iterations :"))
        self.label_37.setText(_translate("MainWindow", "N ="))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Enter additional conditions "))
        self.label_38.setText(_translate("MainWindow", "Value table :"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Result"))
        self.ButtStart3.setText(_translate("MainWindow", "Run"))
        self.plot6.setTabText(self.plot6.indexOf(self.tab_2), _translate("MainWindow", " Numerical solution of three-dimensional systems"))
        self.label_97.setText(_translate("MainWindow", "w ="))
        self.label_98.setText(_translate("MainWindow", "Set the number of iterations :"))
        self.label_94.setText(_translate("MainWindow", "alfa2 = x(t -__)"))
        self.label_89.setText(_translate("MainWindow", "h ="))
        self.label_90.setText(_translate("MainWindow", "alfa1 = x(t -__)"))
        self.label_91.setText(_translate("MainWindow", "Set helper options :"))
        self.label_93.setText(_translate("MainWindow", "Set grid integration step :"))
        self.label_92.setText(_translate("MainWindow", "Initial function by \'x\' ="))
        self.label_80.setText(_translate("MainWindow", "alfa3 = x(t -__)"))
        self.label_96.setText(_translate("MainWindow", "x\' ="))
        self.label_78.setText(_translate("MainWindow", "Enter a system of differential equations :"))
        self.label_95.setText(_translate("MainWindow", "Enter initial functions :"))
        self.label_100.setText(_translate("MainWindow", "N = "))
        self.label_75.setText(_translate("MainWindow", "Value table :"))
        self.ButtStart6.setText(_translate("MainWindow", "Run"))
        self.plot6.setTabText(self.plot6.indexOf(self.tab_8), _translate("MainWindow", "Delay differential equations (ODE case)"))
        self.label_99.setText(_translate("MainWindow", "w ="))
        self.label_74.setText(_translate("MainWindow", "Initial function by \'x\' ="))
        self.label_84.setText(_translate("MainWindow", "h ="))
        self.label_86.setText(_translate("MainWindow", "beta2 = y(t -__)"))
        self.label_85.setText(_translate("MainWindow", "beta1 = y(t -__)"))
        self.label_67.setText(_translate("MainWindow", "beta3 = y(t -__)"))
        self.label_72.setText(_translate("MainWindow", "Enter a system of differential equations :"))
        self.label_70.setText(_translate("MainWindow", "alfa3 = x(t -__)"))
        self.label_71.setText(_translate("MainWindow", "alfa1 = x(t -__)"))
        self.label_73.setText(_translate("MainWindow", "Set helper options :"))
        self.label_76.setText(_translate("MainWindow", "Enter initial functions :"))
        self.label_68.setText(_translate("MainWindow", "Set grid integration step :"))
        self.label_79.setText(_translate("MainWindow", "x\' ="))
        self.label_81.setText(_translate("MainWindow", "y\' ="))
        self.label_77.setText(_translate("MainWindow", "Initial function by \'y\' ="))
        self.label_83.setText(_translate("MainWindow", "N = "))
        self.label_82.setText(_translate("MainWindow", "Set the number of iterations :"))
        self.label_69.setText(_translate("MainWindow", "alfa2 = x(t -__)"))
        self.label_101.setText(_translate("MainWindow", "v ="))
        self.label_66.setText(_translate("MainWindow", "Value table :"))
        self.ButtStart4.setText(_translate("MainWindow", "Run"))
        self.plot6.setTabText(self.plot6.indexOf(self.tab_7), _translate("MainWindow", "Delay differential equations 2D"))
        self.label_54.setText(_translate("MainWindow", "gamma1 = z(t -__)"))
        self.label_53.setText(_translate("MainWindow", "beta3 = y(t -__)"))
        self.label_61.setText(_translate("MainWindow", "Set grid integration step :"))
        self.label_49.setText(_translate("MainWindow", "alfa2 = x(t -__)"))
        self.label_50.setText(_translate("MainWindow", "alfa3 = x(t -__)"))
        self.label_46.setText(_translate("MainWindow", "alfa1 = x(t -__)"))
        self.label_47.setText(_translate("MainWindow", "Enter a system of differential equations :"))
        self.label_48.setText(_translate("MainWindow", "Set helper options :"))
        self.label_44.setText(_translate("MainWindow", "Initial function by \'x\' ="))
        self.label_55.setText(_translate("MainWindow", "gamma2 = z(t -__)"))
        self.label_43.setText(_translate("MainWindow", "Enter initial functions :"))
        self.label_45.setText(_translate("MainWindow", "Initial function by \'y\' ="))
        self.label_57.setText(_translate("MainWindow", "Initial function by \'z\' ="))
        self.label_58.setText(_translate("MainWindow", "x\' ="))
        self.label_60.setText(_translate("MainWindow", "z\' ="))
        self.label_59.setText(_translate("MainWindow", "y\' ="))
        self.label_63.setText(_translate("MainWindow", "Set the number of iterations :"))
        self.label_65.setText(_translate("MainWindow", "N = "))
        self.label_62.setText(_translate("MainWindow", "h ="))
        self.label_51.setText(_translate("MainWindow", "beta1 = y(t -__)"))
        self.label_52.setText(_translate("MainWindow", "beta2 = y(t -__)"))
        self.label_56.setText(_translate("MainWindow", "gamma3 = z(t -__)"))
        self.label_64.setText(_translate("MainWindow", "Value table :"))
        self.ButtStart5.setText(_translate("MainWindow", "Run"))
        self.plot6.setTabText(self.plot6.indexOf(self.tab_6), _translate("MainWindow", "Delay differential equations 3D"))

